### ISSUE TITLE
Create a couchdb view to export the toc for stock search

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/stock-manager-app#12]
Probably 2 views:
* structure search
* 'quick search' (array filter)

##
* general.name : name
* general.description
* general.oclCode
* general.mf, general.mw: mf, fw
* identifier.rn.value -> cas (Chemical Abstract Service, generates what they call registry number (RN))
* last status information
* index ? (or in a second view ?)

**Comment by stropitek** [comment]
For now I created 1 view that contains the index
