### ISSUE TITLE
Be able to print label

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/stock-manager-app#16]
At first we could create a simple node server that runs locally on port 8080 and that will allow to use the view 

https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F45f944c179a1f9002fe37a493d5a6527%2Fview.json

The node application has the following entry points:
* loadFormats
* saveFormats
* listSerialPorts
* getFormatNames
* print
  * formatName
  * data: stringify of the object

Formats could be associated with a serial port. We could think about a computer having more than one label printer (different size of label, color of labels for example)

**Comment by stropitek** [comment]
Done
