### ISSUE TITLE
Define status

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/stock-manager-app#9]
* 100 : Order to confirm 
* 200 : Product to order 
* 300 : Product ordered 
* 400 : Product arrived 
* 500 : Product released 
* 600 : Product to revalidate 
* 700 : Product refused 
* 800 : Product expired
* 900 : Product lost
* 1000 : Product empty 

"Quick add stock" add the products with the status 500. This could be configured from the database preferences.

**Comment by stropitek** [comment]
https://github.com/cheminfo-js/visualizer-helper/blob/master/eln/StockHelper.js
